---
apiVersion: v1
kind: Namespace
metadata:
  name: baget
  labels:
    goldilocks.fairwinds.com/enabled: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: baget-data-claim
  namespace: baget
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: freenas-iscsi-csi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: baget-env
  namespace: baget
data:
    ApiKey: CHANGE_ME
    Storage__Type: FileSystem
    Storage__Path: /var/baget/packages
    Database__Type: Sqlite
    Database__ConnectionString: Data Source=/var/baget/baget.db
    Search__Type: Database
    AllowPackageOverwrites: "true"
    PackageDeletionBehavior: HardDelete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baget
  namespace: baget
  labels:
    app: baget
spec:
  selector:
    matchLabels:
      app: baget
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: baget
    spec:
      containers:
      - name: baget
        image: loicsharma/baget:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /v3/index.json
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 30
        envFrom:
          - configMapRef:
              name: baget-env
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: baget-data
          mountPath: /var/baget
      volumes:
        - name: baget-data
          persistentVolumeClaim:
            claimName: baget-data-claim
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: baget
  namespace: baget
  labels: 
    app: baget
spec:
  type: ClusterIP
  selector:
    app: baget
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
