# Install Budibase via helm:
#
# helm repo add budibase https://budibase.github.io/budibase/
# helm repo update
# helm install --create-namespace --namespace budibase budibase budibase/budibase --set couchdb.clusterSize=1 --set ingress.nginx=false
# helm install --create-namespace --namespace budibase budibase budibase/budibase --set couchdb.enabled=false --set couchdb.clusterSize=1 --set ingress.nginx=false --set couchdb.url=http://couchdb-svc-couchdb.couchdb.svc:5984 --set couchdb.user=admin --set couchdb.password=CHANGE_ME

# Edit seedlistini ConfigMap and remove seedlist:

# [cluster]
# seedlist = couchdb@couchdb-couchdb-0.couchdb-couchdb.couchdb.svc.cluster.local
#
---
apiVersion: v1
kind: Service
metadata:
  name: "kube-dns"
  namespace: kube-system
spec:
  type: ExternalName
  externalName: "rke2-coredns-rke2-coredns.kube-system.svc.cluster.local"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budibase-ingress
  namespace: budibase
  labels:
    app.kubernetes.io/name: budibase
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '30'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
spec:
  tls:
    - hosts:
        - budibase.lucasnet.int
      secretName: lucasnet-tls
  rules:
    - host: budibase.lucasnet.int
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: proxy-service
                port:
                  number: 10000
