# kubectl exec -ti busybox-2 -- nslookup mssql-1-np.default.svc.cluster.local
#
apiVersion: v1
kind: Pod
metadata:
  name: busybox-1
  namespace: default
spec:
  containers:
  - name: busybox-1
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  nodeName: rancher.internal
