# Elasticsearch install via helm (no operator)
#
# helm repo add elastic https://helm.elastic.co
# helm repo update
# helm install elasticsearch elastic/elasticsearch -f elastic-helm-values.yaml  --namespace=elk --create-namespace
#
# Test:  curl -k -XGET https://elastic:CHANGE_ME@elastic.lucasnet.int/_cluster/health?pretty=true
#
# Elasticsearch-helm-values.yaml
---
replicas: 1
antiAffinity: "soft"
esJavaOpts: "-Xmx256m -Xms256m"
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
resources:
  requests:
    cpu: "100m"
    memory: "1024M"
  limits:
    cpu: "500m"
    memory: "1024M"
---
# Kibana Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: elk
spec:
  tls:
    - hosts:
        - elk.lucasnet.int
      secretName: lucasnet-tls
  rules:
    - host: elk.lucasnet.int
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana-kibana
                port:
                  number: 5601
---
# ElasticSearch Load Balancer
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: first-pool
  labels:
    app: elasticsearch
  name: elasticsearch-lb
  namespace: elk
spec:
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  selector:
    app: elasticsearch-master
  type: LoadBalancer
---
# Bootstrap index:
# PUT logstash-2023.01.19
# {
#   "aliases": {
#     "logstash": {
#       "is_write_index": true
#     }
#   }
# }

# PUT _template/logstash_template
# {
#   "index_patterns": [
#     "logstash-*"
#   ],
#     "settings": {
#       "number_of_shards": 1,
#       "number_of_replicas": 1,
#       "index.lifecycle.name": "3-days-no-rollover",
#       "index.lifecycle.rollover_alias": "logstash"
#     }
# }

# PUT logstash-2023.05.14/_settings
# {
#   "index.mapping.total_fields.limit": 2000
# }
