# Install helm repo:
#   helm repo add fluent https://fluent.github.io/helm-charts
#   helm repo update
#   helm upgrade --install fluent-bit fluent/fluent-bit --namespace logging --create-namespace
#
# Update configmap:

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.0.8
    helm.sh/chart: fluent-bit-0.21.7
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: logging
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-1-es-http.elastic-system
        Logstash_Format On
        Retry_Limit 5
        Replace_Dots On
        HTTP_User elastic
        HTTP_Passwd CHANGE_ME
        tls On
        tls.verify Off
        Type  _doc

    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-1-es-http.elastic-system
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit 5
        Replace_Dots On
        HTTP_User elastic
        HTTP_Passwd CHANGE_ME
        tls On
        tls.verify Off
        Type  _doc
