apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-app
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
      tier: frontend
  template:
    metadata:
      labels:
        app: guacamole
        tier: frontend
    spec:
      containers:
        - name: guacamole-app
          image: guacamole/guacamole:1.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: GUACD_HOSTNAME
              value: "guacamole-daemon"
            - name: GUACD_PORT
              value: "4822"
            - name: LDAP_HOSTNAME
              value: "192.168.0.50"
            - name: LDAP_USER_BASE_DN
              value: "OU=Users,OU=Lucasnet,DC=lucasnet,DC=int"
            - name: LDAP_USERNAME_ATTRIBUTE
              value: "sAMAccountName"
            - name: LDAP_SEARCH_BIND_DN
              value: "CN=join_ad_sa,OU=ServiceAccounts,OU=Lucasnet,DC=lucasnet,DC=int"
            - name: LDAP_SEARCH_BIND_PASSWORD
              value: "CHANGE_ME"
            - name: LDAP_CONFIG_BASE_DN
              value: "OU=Guacamole,OU=Hosting,OU=Lucasnet,DC=lucasnet,DC=int"
          ports:
            - name: guacamole-app
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "750m"
