apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv-1
  namespace: default
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 10.126.29.66:3260
     iqn: iqn.2005-10.org.freenas.ctl:freenas-iscsi-3
     lun: 0
     fsType: 'xfs'
     readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-pvc-1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: iscsi-pv-1
