# Jaeger helm install:
#
# https://www.jaegertracing.io/docs/1.45/operator/
#
# Install Certmanager:
#   kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
#
# helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
# helm repo update
# helm install jaeger-operator jaegertracing/jaeger-operator --namespace jaeger --create-namespace
# 
# kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD=CHANGE_ME --from-literal=ES_USERNAME=elastic --namespace jaeger

---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  namespace: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elastic:CHANGE_ME@elastic.lucasnet.int
        index-prefix: jaeger
        tls:
          ca: /es/certificates/lucasnet-ca.pem
  volumeMounts:
    - name: lucasnet-ca
      mountPath: /es/certificates/lucasnet-ca.pem
      subPath: lucasnet-ca.pem
      readOnly: true
  volumes:
    - name: lucasnet-ca
      configMap:
        name: lucasnet-ca
  ingress:
    enabled: false
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: jaeger
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: jaeger
    app.kubernetes.io/component: query-ingress
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simplest-query
    app.kubernetes.io/part-of: jaeger
spec:
  tls:
    - hosts:
        - jaeger.lucasnet.int
      secretName: lucasnet-tls
  rules:
    - host: jaeger.lucasnet.int
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simplest-query
                port:
                  number: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-np
  namespace: jaeger
spec:
  type: NodePort
  ports:
    - port: 14267
      targetPort: 14267
      nodePort: 31000
      name: c-tchan-trft
    - port: 14268
      targetPort: 14268
      nodePort: 31001
      name: c-binary-trft
  selector:
    app: jaeger