# KubectlBotApi developed by mike@lucasnet.org for executing kubectl commands via Api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectlbot-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kubectlbot
rules:
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/eviction
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - patch
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
    apiGroups:
      - apps
    resources:
      - statefulsets
  - verbs:
      - get
      - list
    apiGroups:
      - extensions
    resources:
      - daemonsets
      - replicasets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectlbot-clusterrole-bind
subjects:
  - kind: ServiceAccount
    name: kubectlbot-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kubectlbot
---
apiVersion: v1
kind: Service
metadata:
  name: kubectlbotapi-nodeport
  namespace: default
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30100
  selector:
    app: kubectlbotapi
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: kubectlbotapi-apikey
  namespace: default
type: Opaque
data:
  apikey: CHANGE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: wild-hpl-com-pfx
  namespace: default
type: Opaque
data:
  wild.hpl.com.pfx: >-
    MIIP5gIBAzCCD6IGCSqGSIb3DQEHAaCCD5MEgg+PMIIPizCCBjIGCSqGSIb3DQEHAaCCBiMEggYfMIIGGzCCBhcGCyqGSIb3DQEMCgECoIIE9jCCBPIwHAYKKoZIhvcNAQwBAzAOBAhnyZ4E1AUDFgICB9AEggTQ4AO90JNoh5jdC/tFlS0AF7si3+wqHBTz/gCs4k9EpBz7eecSRZ2ZuzLBojMFl4O+Gnjm3RSdHJ7pheIF8O5ijmjI5tdy1CAFcyfpBRWPonFLMAskTZl3KjRu4ALSN4RfYAg78Ef4yEwgSNE7UfS5lqFDboCtQ0F2iIu5j4khhMmHMjwiJcKzEz7XTBobAoyu1Bt70x1SfzG90jvIX1uE/lo8EoURWIn0m7JKwtxOrTlfk/D4ZyJPYXpo0ZALII5gT5xMgLjeMh3CuTXLdONRezipYjZHiBAh909rEhGGIKXBkclUGeee0qictMHp/2012nv1JRDgj65BR0zHtOlrc7Awf8CCcFmLLmnVVje0YM5pcraEzrkMSmPHzVBvDC8TutMfj5+7ZqBQc4FyyLksgU2ZoocHNAqO7HTJGqVWtO6i8aRm90PsCa9z4zhvyRV1rw3KTYUrzoGTonapz0mZjWnznOZ+P+zVkYjO4YYFknMShS3MHDCAL3Qi7DMRacjjVKdgPXLb+WAA0MDh+/VUy0fd3zmZfdCnKfW8tTcANZfuUN0MRRFdcKVvu9dL7C5QxbpCQ/84ThoiQ7oMmDupP8ScUvvguUiSUdAPehIDyFrhg+NuFM8Du5kGrExjhW4IQDOUO3zrK427jmibMOTC8DoAYkM/epsRCZOeNv+DhCniEdCJVm4ILJLfBvP6ET3gL2TuJk198bOm9/DhQUfiT3eh07eCAqiMEYoSwAbmHs1m5+D2UTWLA0wh3QeHZKuGRQ490qu7GBgKKzP4bThskca/FYNSJzhgZTzHdiE4rPat01JHGL6L2im7HTJnDMoZEuJsC90hXjtzrmlbBp2eAYQRNGgv9vFtyDmKXWpv/Ikrsz0Z5BQJ9rLtdGkOkFWOA/QSq9rcsepWKSC3yLWsRZ99k9vb8ODORqN/nvuZFWdT2K0EHCt48+MRpbj/zLwS2XkAuurfpGbo2c2s5OyU3HuZZm+mgUYChfVVIevtcOqdfbpJoQ7VP9PR99a9D0waxb7fnfVWo47ugpEidlhewYPAYGAku6vIcBH5nY0A2wVGUwcsbIm9IL7FJ5S18VY+BLHpxDyvJ8/Irw0B8oXB3aaoZwCr+Lb21+kn48992tZohsasZzM/I84oTjt0DnBaTtptkOa+3f5TbDl4puoSFguPUtieXzNfBtHLg4SfPQ/5s5+99Ou7si+R7iEODmrcLgPABuJaCFi1bF7yler8zb42JDP+JZd6ugm0k4dr5GMBTCMkfYg93YroTpFhzHe9Bdl3HGWokeq6ywItD6AcoUFcJADeLlXyXPF36lW8kAmmqnnoaRkpkbA43EBhgGVlJbaenNlp/WoJPrMDF4a31CNk3S9mfp08Gg24XWSyoO7hCslOAlFl9Swu4jrlD3kwAtew5TF5LV0RPwzxGfqopnP7nsEj//4m141M2G5d8GXC5HoQaHpOZQ+IwBMhj/wZ4F4066I4fr7Z+fRY68n+bXlZ0Qm/BhU5Xm01nOY6oG6udtzPpe4hPI4lCBhB2/gU4SBnzVobWFR6sTGMIWglfKBtvbVzPsOwxagxeSUVtlnKueTlIpttOhp7V8vahp6Wa0HCxg7kX916pLL23eVsRxiv7wwXDLFXtpdXVNMoh3sxggEMMA0GCSsGAQQBgjcRAjEAMBMGCSqGSIb3DQEJFTEGBAQBAAAAMGkGCSsGAQQBgjcRATFcHloATQBpAGMAcgBvAHMAbwBmAHQAIABSAFMAQQAgAFMAQwBoAGEAbgBuAGUAbAAgAEMAcgB5AHAAdABvAGcAcgBhAHAAaABpAGMAIABQAHIAbwB2AGkAZABlAHIwewYJKoZIhvcNAQkUMW4ebAB0AGUALQBXAGUAYgBTAGUAcgB2AGUAcgA1AHkAZQBhAHIALQA5ADcAMwA2AGUAYgBjAGIALQAwADkANwA2AC0ANAA3AGIAMgAtAGEAOABjADYALQBkAGIAZQAxADQAMwA4ADgAYgBmAGEAOTCCCVEGCSqGSIb3DQEHAaCCCUIEggk+MIIJOjCCBZ0GCyqGSIb3DQEMCgEDoIIFSjCCBUYGCiqGSIb3DQEJFgGgggU2BIIFMjCCBS4wggQWoAMCAQICE2AAAAk4iqEeyHQaGc8AAAAACTgwDQYJKoZIhvcNAQENBQAwOzETMBEGCgmSJomT8ixkARkWA2NvbTETMBEGCgmSJomT8ixkARkWA2hwbDEPMA0GA1UEAxMGSFBMLUNBMB4XDTIzMDIwMTE0NDUzN1oXDTI0MDYyNTIxNDIxMVowEjEQMA4GA1UEAxMHaHBsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALC2neyW1DaCTmBTsMTqqZAik2UDYZn1YE12zXWjTX89uAOOEgxV17tBbIPg1QFbItYEEt2wDPZPnSXXLF9eJTjcwwzZ7CSiLbj1G91SPzudQVUGs765ooRfrOocgh2IyJBqRhP1zI9ljhGeRIDj6x1w2lwbcQje2hZY6iNR65LAwcf3/6+/wrSbP6AsK2J2axXV+z+8vKNpXBcgnYBSfHNHpQf9C7H/AkyvzFHJGL/G9SHI/91l0q5pPmMenxIx1d9Lwxlqwm4BoU9kw/NVSWiikwPtlXiolbWgKhEB2o5wxtiGTyqqdKOnZsMHMI41gM3wjQqVY/ysDEeSfaGeacUCAwEAAaOCAlIwggJOMD4GCSsGAQQBgjcVBwQxMC8GJysGAQQBgjcVCIPpuCCCgJsXh/GRGoKKhSKBjO8egTyDsftygu2vCAIBZAIBEDATBgNVHSUEDDAKBggrBgEFBQcDATALBgNVHQ8EBAMCBaAwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDATAdBgNVHQ4EFgQU7syXLZ6OD+IfCx9QVpaBwDT9ZE0wFAYDVR0RBA0wC4IJKi5ocGwuY29tMB8GA1UdIwQYMBaAFAFRoR1MxdLPh6MLW+jUQeVSafcyMIG/BgNVHR8EgbcwgbQwgbGgga6ggauGgahsZGFwOi8vL0NOPUhQTC1DQSxDTj1IUEwtQ0EsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9aHBsLERDPWNvbT9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQwgbQGCCsGAQUFBwEBBIGnMIGkMIGhBggrBgEFBQcwAoaBlGxkYXA6Ly8vQ049SFBMLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWhwbCxEQz1jb20/Y0FDZXJ0aWZpY2F0ZT9iYXNlP29iamVjdENsYXNzPWNlcnRpZmljYXRpb25BdXRob3JpdHkwDQYJKoZIhvcNAQENBQADggEBAB3RUEhhfEWOGZJ3A9SQd0qCG1CvqP7g1flRBFWdmuQk/NsYDUEUigKzvsKdlXJ8xuIQll7BNfAmVpUo86dg+EBso1ODSBxXX1RuI1KvjvUtpbHMRRxM+ShooaiQT31K6bNbr4uixBeI3uHdHBb5yvGW1sb6/UoV3qWvHgduwVUUbKB+ChfkypuApsf2qEGmuEep1WwK+FmCFB2EKW6P5jq2xN/s9hhDA1HSPQyzqL3PdqsBKrFL0u7bjvVE/M+VfrJs2c74LW1Oojv0Tnc7rEhIajqwH3U9BL/9FGLeurIYANHrVkgnSqq9zTUBk22H76ZZml8mwPN+WIsfJ+ZMCLwxQDATBgkqhkiG9w0BCRUxBgQEAQAAADApBgkqhkiG9w0BCRQxHB4aAHcAaQBsAGQALgBoAHAAbAAuAGMAbwBtAAAwggOVBgsqhkiG9w0BDAoBA6CCA4IwggN+BgoqhkiG9w0BCRYBoIIDbgSCA2owggNmMIICTqADAgECAhA4plBq26dBkUrU8d6ek1feMA0GCSqGSIb3DQEBDQUAMDsxEzARBgoJkiaJk/IsZAEZFgNjb20xEzARBgoJkiaJk/IsZAEZFgNocGwxDzANBgNVBAMTBkhQTC1DQTAeFw0xOTA2MjUyMTMyMTFaFw0yNDA2MjUyMTQyMTFaMDsxEzARBgoJkiaJk/IsZAEZFgNjb20xEzARBgoJkiaJk/IsZAEZFgNocGwxDzANBgNVBAMTBkhQTC1DQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJCIg8F/FXLANdJJr9mEH3VIur2ZMNYcq3Nbe7Ll8ULgP/DnzW7PeKXVKtl/fV/LLYlES1K648BBegMAuxE38IPCyBNhCEh1z/FCVkWoJTKvDqYoV6HFQQOgzSBDimYfMjcyEvlnl697sUAm73Me7v/O54fdlBGAH8FKt+mD1ACEdLv/1nBE22/8rqbX4h/1qyJgqvFhmxsaSEN+dRurjEgttXROxMH1BKMePSmrebW6sWprERlYX+Q5m4m4fPD2ZP3KyFj2DrbK17hWFI3s58AO86A6JT3hEz0DQnb9V5PCG3c/97QbVJVSxxYk8QqNkGNmS9nnOkpbpiB9B9S0jsCAwEAAaNmMGQwEwYJKwYBBAGCNxQCBAYeBABDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFAFRoR1MxdLPh6MLW+jUQeVSafcyMBAGCSsGAQQBgjcVAQQDAgEAMA0GCSqGSIb3DQEBDQUAA4IBAQBm9Mgtqffgql7FRyTJftPOGoIc2iQ7+rOcEAn3FGZUgS5yiCBbIjQ4eYRtCKZ5XhL5xQ/Qp/shio7woXntUtjrV7KZb7bA0sYlc3osLb9u58jm2e3hoPEa4vMUpYLGd6Hi/5rqhFRedXwaS3Daaph9IwzYXRKvvpuyGdATrEBKQvchL9y/bgdl+jAC/J8kC5wXz6f9zIeWwe/Qx4EyrVq+D+4kHM5+YEFXqL6286j5KNpDg2IktqqPxsrhY6oH5G8ROtKHRMEg4Lkn4eXz4xz2tpORtMq2NWITdgM557UN7fgIcwM1MQykFYISgrMdDSJejWUcTZhp41QTxM2x5Y9oMQAwOzAfMAcGBSsOAwIaBBReMUy6w2LESLuU9tq0wHh/2hO11wQUFSm8IuWS1G060CJMObY9MZfn7J0CAgfQ
---
apiVersion: v1
kind: Secret
metadata:
  name: wild-hpl-com-pfx-password
  namespace: default
type: Opaque
data:
  password: CHANGE_ME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectlbotapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectlbotapi
  template:
    metadata:
      labels:
        app: kubectlbotapi
    spec:
      volumes:
        - name: tls-cert
          secret:
            secretName: wild-hpl-com-pfx
            defaultMode: 420
      containers:
        - name: kubectlbotapi
          image: dev-harbor.dev.rph.int/michael.lucas/kubectlbotapi:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+:80;https://+:443
            - name: ASPNETCORE_Kestrel__Endpoints__HttpsInlineCertFile__Url
              value: https://*:443
            - name: >-
                ASPNETCORE_Kestrel__Endpoints__HttpsInlineCertFile__Certificate__Path
              value: /app/ssl/wild.hpl.com.pfx
            - name: >-
                ASPNETCORE_Kestrel__Endpoints__HttpsInlineCertFile__Certificate__Password
              valueFrom:
                secretKeyRef:
                  name: wild-hpl-com-pfx-password
                  key: password
            - name: ASPNETCORE_APIKEY
              valueFrom:
                secretKeyRef:
                  name: kubectlbotapi-apikey
                  key: apikey
          volumeMounts:
            - name: tls-cert
              readOnly: true
              mountPath: /app/ssl
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: kubectlbot-sa
      serviceAccount: kubectlbot-sa
