# Install Lemmy via Helm

# helm repo add ananace-charts https://ananace.gitlab.io/charts
# helm install lemmy ananace-charts/lemmy --set serverName=lemmy.lucasnet.int --set admin.email=mike@lucasnet.org --set config.siteName="Lucasnet Lemmy" --namespace lemmy --create-namespace
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lemmy
  namespace: lemmy
  labels:
    app.kubernetes.io/instance: lemmy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: lemmy
    app.kubernetes.io/version: 0.18.2
    helm.sh/chart: lemmy-0.4.1
    k8slens-edit-resource-version: v1
  annotations:
    meta.helm.sh/release-name: lemmy
    meta.helm.sh/release-namespace: lemmy
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - lemmy.lucasnet.int
        - lemmy.lucasnet.org
      secretName: lucasnet-tls
  rules:
    - host: lemmy.lucasnet.int
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lemmy-proxy
                port:
                  number: 80
