apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: local-stor-test
  name: local-stor-test
spec:
  serviceName: local-service
  replicas: 3
  selector:
    matchLabels:
      app: local-stor-test
  template:
    metadata:
      labels:
        app: local-stor-test
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - local-stor-test
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: test-container
        image: k8s.gcr.io/busybox
        command:
        - "/bin/sh"
        args:
        - "-c"
        - "sleep 100000"
        volumeMounts:
        - name: local-volume
          mountPath: /data
      nodeSelector:
        nodetype: worker
  volumeClaimTemplates:
  - metadata:
      name: local-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
