# Install mongodb helm chart:
#
# https://artifacthub.io/packages/helm/bitnami/mongodb
#
# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm repo update
# helm install mongodb bitnami/mongodb --namespace mongodb --create-namespace --set architecture="replicaset"
#
# OR --> Install mongodb operator:
#
# helm install community-operator mongodb/community-operator --namespace mongodb
#
# ConnectionString:  mongodb://admin:CHANGE_ME@mongodb.lucasnet.int:27017/?directConnection=true&authMechanism=SCRAM-SHA-256
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-1
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
  namespace: mongodb
type: Opaque
stringData:
  password: CHANGE_ME
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-lb
  namespace: mongodb
  labels:
    app: mongodb-svc
spec:
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-1-svc
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster