# Install mongodb helm chart:
#
# https://artifacthub.io/packages/helm/bitnami/mongodb
#
# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm repo update
# helm install mongodb bitnami/mongodb --namespace mongodb --create-namespace --set architecture="replicaset"

# NAME: mongodb
# LAST DEPLOYED: Tue Apr 11 05:45:25 2023
# NAMESPACE: mongodb
# STATUS: deployed
# REVISION: 1
# TEST SUITE: None
# NOTES:
# CHART NAME: mongodb
# CHART VERSION: 13.9.4
# APP VERSION: 6.0.5

# ** Please be patient while the chart is being deployed **

# MongoDB&reg; can be accessed on the following DNS name(s) and ports from within your cluster:

#     mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017
#     mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017

# To get the root password run:

#     export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace mongodb mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 -d)

# To connect to your database, create a MongoDB&reg; client container:

#     kubectl run --namespace mongodb mongodb-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:6.0.5-debian-11-r4 --command -- bash

# Then, run the following command:
#     mongosh admin --host "mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017,mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD


# Install mongodb operator:
#
# helm install community-operator mongodb/community-operator --namespace mongodb
#
# ConnectionString:  mongodb://admin:CHANGE_ME@mongodb.lucasnet.int:27017/?directConnection=true&authMechanism=SCRAM-SHA-256
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
  namespace: mongodb
type: Opaque
stringData:
  password: CHANGE_ME
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-lb
  namespace: mongodb
  labels:
    app: mongodb-svc
spec:
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-svc
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster