apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment-1
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql-1
  template:
    metadata:
      labels:
        app: mssql-1
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssql-1
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_AGENT_ENABLED
          value: "True"
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: iscsi-pvc-1
---
apiVersion: v1
kind: Service
metadata:
   name: mssql-1-np
spec:
  type: NodePort
  ports:
  - port: 1433 
    nodePort: 31433
    protocol: TCP
  selector:
    app: mssql-1