---
kind: Namespace
apiVersion: v1
metadata:
  name: smokeping
  labels:
    name: smokeping
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-config
  namespace: smokeping
  labels:
    k8s-app: smokeping
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smokeping-data
  namespace: smokeping
  labels:
    k8s-app: smokeping
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smokeping
  namespace: smokeping
  labels:
    k8s-app: smokeping
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      k8s-app: smokeping
  template:
    metadata:
      labels:
        k8s-app: smokeping
    spec:
      containers:
      - name: smokeping
        image: lscr.io/linuxserver/smokeping:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/config"
            name: config
          - mountPath: "/data"
            name: data
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "America/Chicago"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: smokeping-config
        - name: data
          persistentVolumeClaim:
            claimName: smokeping-data
---
apiVersion: v1
kind: Service
metadata:
  name: smokeping-svc
  namespace: smokeping
  labels:
    k8s-app: smokeping
spec:
  ports:
  - port: 7000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: smokeping
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: smokeping-ingress
  namespace: smokeping
  annotations:
spec:
  rules:
  - host: smokeping.dev.rph.int
  - http:
      paths:
      - backend:
          service:
            name: smokeping-svc
            port:
              number: 7000
        path: /
        pathType: Prefix
