apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma-metrics
  namespace: monitoring
  labels:
    app: uptime-kuma-metrics
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: uptime-kuma
    scheme: http
    basicAuth:
      password:
        name: uptime-kuma-auth
        key: password
      username:
        name: uptime-kuma-auth
        key: username
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: uptime-kuma
---
apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-auth
  namespace: monitoring
data:
  password: CHANGE_ME
  username: QWRtaW4=