# Install Weave Gitops dashboard via gitops command:
#
#    https://docs.gitops.weave.works/docs/next/installation/weave-gitops/

# export GITHUB_USER=mtlucas
# curl --silent --location "https://github.com/weaveworks/weave-gitops/releases/download/v0.18.0/gitops-$(uname)-$(uname -m).tar.gz" | tar xz -C /tmp
# sudo mv /tmp/gitops /usr/local/bin
# gitops version

# git clone https://github.com/$GITHUB_USER/fluxcd
# cd fluxcd

# PASSWORD="CHANGE_ME"
# gitops create dashboard ww-gitops \
#   --password=$PASSWORD \
#   --export > ./clusters/my-cluster/weave-gitops-dashboard.yaml

# git add -A && git commit -m "Add Weave GitOps Dashboard"
# git push

# kubectl get pods -n flux-system

# Ingress:
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-ingress
  namespace: flux-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '30'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
spec:
  tls:
    - hosts:
        - gitops.lucasnet.int
      secretName: lucasnet-tls
  rules:
    - host: gitops.lucasnet.int
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ww-gitops-weave-gitops
                port:
                  number: 9001
